name: Run unit tests

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-24.04
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile robot code
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
          comment: true
